### PR TITLE
Add grunt task, license, gitignore to the project.

### PR DESCRIPTION
**Pull request by zaggino**
Add jshint and grunt to check for potential code issues and help to keep code clean.
Also probably a good idea would be to put code files under `src` folder.

### CODE REVIEW

**Comment by zaggino** [comment]
It won't effect registry at all, but it's a good practice to check code for errors and formatting. You can change any options in the jshint style you want. I for example tend to use only one type of quotes across project but I've seen that your one is using both ' and " so I disabled to check for it.

**Comment by jrowny** [comment]
I was referring to changing the package name from  "jrowny.brackets.snippets" to "jrowny.brackets-snippets" I think the registry uses the package name to identify it. I'm worried that if the package name changes that people with the extension won't get the notification to update.

**Comment by zaggino** [comment]
Ah, you're probably right about that, didn't occur to me. I'll change it back.

**Comment by zaggino** [comment]
As far as the versioning goes, it'd be probably best if you'd handle the version changes when you push it to the registry.

**Comment by jrowny** [comment]
Cool, my plan would be to make a tag where the version loses the -dev.

**Pull request merged**
