### PR TITLE
Reduce jitter (inline input form)

### PR DESCRIPTION
**Pull request by ThaisRobba**
This tiny patch adds some space so that the input form doesn't jitter as much as it does right now.
It also cleans up the span style (it had a typo and honestly did nothing).

### CODE REVIEW

**Comment by pmario** [comment]
@OttoRobba Hi, where is your forked repo?

**Comment by ThaisRobba** [comment]
@pmario I believe it is long gone - this is from two years ago, I'm closing it.

**Comment by pmario** [comment]
@OttoRobba That's sad. So I need to recreate it. Did your version work well? Looking at your gifs it's exactly what I'm looking for. ... Or did you find an alternative?

**Comment by ThaisRobba** [comment]
@pmario You can simply look at the diffs above. I'm currently using Atom, not Brackets.

**Pull request closed without merging**
