### PR TITLE
added hack to ignore dotfiles

### PR DESCRIPTION
**Pull request by chrismatheson**
Im not sure about whitelisting vs blacklisting. i like the ignore dotfiles as they are usual config and not content. Happy to take another look some time in the future, but for now this change is here if you want it :)

### CODE REVIEW

**Comment by jrowny** [comment]
This works fine for now, thanks!

**Comment by cfjedimaster** [comment]
I ran into another issue. I had a .git folder and readme.md in my data dir (long story). What about making the extension ONLY support *.json?

**Comment by jrowny** [comment]
Probably a good idea

**Comment by cfjedimaster** [comment]
I got it done already, too lame for a pull request probably:

```
                                if(entries[i].fullPath.indexOf(".json") >= 0) {
                                    loading.push(loadSnippet(entries[i]));
                                }
```

And to be fair, this would match foo.json.omgusuck. But it got me past Snippets failing to load for me. ;)

**Comment by jrowny** [comment]
Yea, I can do 

```
var len = entries[i].fullPath.length;
if(entries[i].fullPath.substring(len-5, len) === ".json") {
  loading.push(loadSnippet(entries[i]));
}
```

which should work.

**Comment by cfjedimaster** [comment]
Cool. Make it so, and then credit me and pretend my original version wasn't
so lame. ;)

On Sun, Aug 18, 2013 at 4:42 PM, Jonathan notifications@github.com wrote:

> Yea, I can do
> 
> var len = entries[i].fullPath.length;
> if(entries[i].fullPath.substring(len-5, len) === ".json") {
>   loading.push(loadSnippet(entries[i]));
> }
> 
> which should work.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jrowny/brackets-snippets/pull/16#issuecomment-22840670
> .

## 

# 

Raymond Camden, Adobe Developer Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: cfjedimaster

**Pull request merged**
