### PR TITLE
Support for inline snippets

### PR DESCRIPTION
**Pull request by zaggino**
This fixes issue #15

### CODE REVIEW

**Comment by tomengland** [comment]
Great suggestion, I was just about to try and make a suggestion to do this, as console log will always insert new line.

**Comment by jrowny** [comment]
Not sure if it was this pull request or an earlier one, but the current tab spacing is no longer retained for HTML. Seems to be okay in script, but for example, if you do an insert in HTML, it always goes all the way to the left. This may be a completely seperate issue.

**Comment by jrowny** [comment]
Inline snippets sometimes delete trailing text. In the example below, the text after the snippet is deleted.
testing

**Comment by zaggino** [comment]
@jrowny all fixed except the wrong snippet indentation. This issue is caused by old piece of code that was there before my modifications. After insering any snippet, it is indented by CodeMirror.

```
//indent lines
for (x = 0; x < lines.length; x++) {
    editor._codeMirror.indentLine(pos.line + x);
}
```

**Pull request merged**
